### ISSUE TITLE
problem with creating new accounts in version 2022.11.1

### ISSUE THREAD

**Issue by Amhehu** [dani-garcia/bw_web_builds#104]
Hi!
With 2022.11.1 I get an error when an invited user want to create his account (red info popup with plain html text containing "page not found" site). In background I use a self build vaultwarden version 1.26.0. With 2022.10.2 this error does not occur.
![error](https://user-images.githubusercontent.com/54313650/206904814-28c48f2a-0f4f-4059-a4b9-670de8a03211.png)

Thanks in advance, also for this great tool generally! :)

**Comment by BlackDex** [comment]
Are you using the `main` branch of Vaultwarden or the tagged version? Because it should work in the `main` branch.

**Comment by BlackDex** [comment]
Looks like the tagged version, and not main. You need main for this web-vault version.
