### ISSUE TITLE
Link to 2FA recovery might not work properly

### ISSUE THREAD

**Issue by mittler-works** [dani-garcia/bw_web_builds#110]
Hello and thank you for your great work!

I'm not sure if my concern is a desired behavior, but it doesn't feel right.

If for whatever reason I need to reset my second factor, I select `Use another two-step login method` when prompted for the second factor:

![image](https://user-images.githubusercontent.com/70568139/217265974-c1fd1a00-9877-411e-9e68-c046fb1b9eb2.png)

In the dialog that opens, I would like to select `Recovery Code`:

![image](https://user-images.githubusercontent.com/70568139/217266219-a14f282f-5133-49ea-aa1b-99abd125d7a6.png)

But this just opens a link to the Bitwarden Help Center (https://bitwarden.com/help/lost-two-step-device/) instead of leading me to the form to reset my second factor. I think it should open `{{SERVER_URL}}/#/recover-2fa/` instead, so this form is shown:

![image](https://user-images.githubusercontent.com/70568139/217266776-fba91b97-5128-4ae2-b5da-d47280c4b8cc.png)

I think the code responsible for this is either [here](https://github.com/bitwarden/clients/blob/master/libs/angular/src/auth/components/two-factor-options.component.ts#L33) (Branch: master) or [here](https://github.com/bitwarden/clients/blob/web-v2023.1.1/libs/angular/src/components/two-factor-options.component.ts#L33) (Tag: web-v2023.1.1).

**Comment by BlackDex** [comment]
I would suggest to point this out at the repo you link to.
That way it will be fixed for all Bitwarden users, and not just Vaultwarden.

**Comment by mittler-works** [comment]
True, thanks. Wilco. Closing.
