### ISSUE TITLE
AGPL?

### ISSUE THREAD

**Issue by tessus** [dani-garcia/bw_web_builds#111]
Now that the vw server is AGPL, is this going to be AGPL as well? Or will it stay as GPL?

**Comment by BlackDex** [comment]
The Bitwarden client code is GPL, so no. We let those stay compatible.

**Comment by dani-garcia** [comment]
For what it's worth, our patches are so small (and mostly just renaming/hiding/changing values) I'd argue there's barely any need for a license. We could consider changing the license for the logos though, those are original work.

**Comment by tessus** [comment]
Thanks for the replies. Just needed to know what I should put in the RPM spec file. So for now I just keep it as GPL-3.

Closing...
