### ISSUE TITLE
Unable to build on macOS

### ISSUE THREAD

**Issue by TheBlueKingLP** [dani-garcia/bw_web_builds#112]
I am unable to build the webvault on macOS with node+npm. 
To reproduce, follow the build instruction on macOS.

```
bw_web_builds % make full    
./scripts/checkout_web_vault.sh
Input a git ref (commit hash, branch name, tag name, 'master'): master
Using: 'master' to checkout bitwarden/client.
~/bw_web_builds/web-vault ~/bw_web_builds
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 4e4de9812 Bumped web version to 2023.2.0 (#4753)
Your branch is up to date with 'origin/master'.
~/bw_web_builds
~/bw_web_builds/web-vault ~/bw_web_builds
From https://github.com/bitwarden/clients
 * branch                master     -> FETCH_HEAD
Already up to date.
Already on 'master'
Your branch is up to date with 'origin/master'.
~/bw_web_builds
./scripts/patch_web_vault.sh
~/bw_web_builds/web-vault ~/bw_web_builds
Patch file not found, using latest
find: -printf: unknown primary or operator
FAILED: line 15, exit code 1. Press any key to exit...
make: *** [patch-web-vault] Error 1
```

This seems to be caused by the missing `-printf` on `find` provided by macOS(or FreeBSD, since macOS the `find` command is based on FreeBSD one).

**Comment by BlackDex** [comment]
I see some more items which could cause an issue on macOS which have a bare install for example.
Ill see if i can make some adjustments.

Thanks for reporting this.

Besides that btw. I do suggest to use docker/podman to build the vault though.
Also keep in mind that the correct version of npm/node is installed, newer versions could cause issues.

**Comment by BlackDex** [comment]
@TheBlueKingLP thanks for reporting. I have created a PR which should resolve your issues.
