### ISSUE TITLE
Master password: input is required

### ISSUE THREAD

**Issue by pkern** [dani-garcia/bw_web_builds#135]
When logging into Vaultwarden by typing the email and then hitting enter, I land on the password entry with "Input is required." in red and the text box deselected. When I do that on vault.bitwarden.com, I land on the password entry without an error and the text box selected. The main issue I have is that I cannot continue typing to enter the password, instead I need to get the text box in focus again.

![Screenshot from 2023-08-13 12-44-43](https://github.com/dani-garcia/bw_web_builds/assets/42176/685eb33a-191a-45b7-bd56-98a13840fe92)

**Comment by stefan0xC** [comment]
This has been fixed with https://github.com/bitwarden/clients/pull/5139 and should be available since [web-v2023.4.0](https://github.com/bitwarden/clients/releases/tag/web-v2023.4.0).

**Comment by pkern** [comment]
Thank you very much for the super speedy reply! I kinda realized just after posting a) that there were new releases and b) I need to figure out how to test a new version (it's still the default in nixos-23.05 unfortunately). If that's fixed, there's enough incentive for b). :)

**Comment by BlackDex** [comment]
Also, you are either running an old version of the Vaultwarden container image, or using an old version of the web-vault installed your self.

**Comment by BlackDex** [comment]
Try to use unstable then, that seems to be updated to the latest stable
