### ISSUE TITLE
Considering update to node 18?

### ISSUE THREAD

**Issue by dionysius** [dani-garcia/bw_web_builds#136]
We currently receive a warning that we don't match the node version: https://github.com/dani-garcia/bw_web_builds/actions/runs/5842418493/job/15843518701#step:8:290

Upstream defines the project to be built with node 18: https://github.com/bitwarden/clients/blob/web-v2023.7.1/.nvmrc

In my deb packagings I had no issues so far with node 18 and ~~it even yields less warning output~~ (not entirely true, different sometimes).

**Comment by BlackDex** [comment]
It looks like v2023.7.1 is still build using v16 too me:
- https://github.com/bitwarden/clients/actions/runs/5661201560/job/15338609821#step:4:14
- https://github.com/bitwarden/clients/actions/runs/5661201560/job/15338609821#step:5:10

Even the last `Build Web` trigger seems to be using v16: https://github.com/bitwarden/clients/actions/runs/5837240071/job/15832394685#step:5:10

So, until they change there CI/CD to v18, i want to keep it on v16.

**Comment by dionysius** [comment]
I think we should reconsider this going forward, maybe inform upstream.

According to https://nodejs.dev/en/about/releases/ the node 16 LTS **maintenance ends in less than two weeks (2023-09-11)

**Comment by BlackDex** [comment]
Maybe it would be nice to report this to Bitwarden then.
But there are several issues with the cli for example using node 18.

- https://github.com/bitwarden/clients/issues/3984
- https://github.com/bitwarden/clients/issues/5876

So, again, until Bitwarden updates there build workflow too use node 18, and it doesn't cause issues, we stay on 16, EOL or not.
We don't have the manpower or knowledge to maintain our fix issues that arise when deviating.

**Comment by stefan0xC** [comment]
@BlackDex because node 16 does not receive any security updates anymore, I've asked Bitwarden Support and it seems it was an oversight. It will be fixed by https://github.com/bitwarden/clients/pull/6421

**Comment by BlackDex** [comment]
> @BlackDex because node 16 does not receive any security updates anymore, I've asked Bitwarden Support and it seems it was an oversight. It will be fixed by [bitwarden/clients#6421](https://github.com/bitwarden/clients/pull/6421)

I haven't checked if uploading files with the cli still broken now.
Just hope nothing else will break hehe. But if we test it good enough it's fine by me.

**Comment by stefan0xC** [comment]
The fix was merged. As far as I've tested it I also think that it should be fine to update to node 18 but we could also wait for the next release. Either way I have not created a commit since there already is #140 which would implement the same change.

**Comment by BlackDex** [comment]
> The fix was merged. As far as I've tested it I also think that it should be fine to update to node 18 but we could also wait for the next release. Either way I have not created a commit since there already is #140 which would implement the same change.

@stefan0xC no it doesn't. That will cause a conflict since it still uses bullseye. It is also closed. From my point of view you may update it.

**Comment by stefan0xC** [comment]
Ah, you're right. I did not notice. 😳
