### ISSUE TITLE
Make a fork?

### ISSUE THREAD

**Issue by mishushakov** [dani-garcia/bw_web_builds#14]
Hey,
maybe it's better to fork bitwarden's web vault instead of "patching"?

it's easier to update and to keep track of changes (for the maintainers)
thank you for your efforts

**Comment by BlackDex** [comment]
Forking it will not make it easier for us to update.
We would have to merge/rebase etc.. with upstream including the sub-repo's.

We only need to change a few items, and add some CSS to the original source files.
Also, this repo is just right enough to build the needed web-vault files and push that to docker.
