### ISSUE TITLE
BUG: importing json

### ISSUE THREAD

**Issue by obnoxiousish** [dani-garcia/bw_web_builds#144]
not sure if 100% right location, if patchs dont edit the JSON importing at all then just close as i'll open in the official bitwarden web vault repo

Imported .JSON file that was exported from my bitwarden for windows into vaultwarden web,

Expected Result: a successful import

WHAT ACTUALLY HAPPENS ERROR: e.match was null (or == null idr)

Must be a bug as I exported .csv from bitwarden for windows then imported and it worked fine.

Thanks <3(i just cloned the repos now so must be newest version)

**Comment by stefan0xC** [comment]
The patches don't edit the JSON importing at all but it might still be an error in vaultwarden. Please provide more information in https://github.com/dani-garcia/vaultwarden/issues/4005 so we can try to reproduce the issue.

**Comment by BlackDex** [comment]
This is the wrong place. As mentioned at the other ticket, i asked if there were some errors in the logs.
It might be an issue, but that should probably have caused an error.
