### ISSUE TITLE
Applying the patched svg logos is a bit tricky for my downstream packaging

### ISSUE THREAD

**Issue by dionysius** [dani-garcia/bw_web_builds#158]
Referring the latest patching concept for replacing the svg logos: https://github.com/dani-garcia/bw_web_builds/compare/v2024.1.2b...v2024.3.0#diff-e1730edcd85a07aa17d014c073364c575abcf87ef0443f43766c73046cc064b0R45-R50

Reproducibility is quite important for the deb packaging tooling and scripts/code to change the origin source code is *generally* not adviced.

I understand that having the svg file separate allows for easy maintenance. Isn't there a better way to do it? Some thoughts:
- Is there a way/hint to load the svg file and replace the string in this ts file during compiling/transpiling?
- Can this ts file be changed so the svg file is loaded during visit of the page?

In both above solutions the svg file is placed in the normal tree and changes to the ts files can be added to the normal patch file.

**Comment by stefan0xC** [comment]
> I think I found a fairly maintainable solution.

What's the solution?

**Comment by dionysius** [comment]
I added [similar (a bit less change resistant) sed replace commands pre-compilation](https://github.com/dionysius/vaultwarden-web-vault-deb/commit/3dee83daec42a2ac6926a0fdc0db59b41379ce79#diff-889c5495b68d2a0c0d1f238818716a71939918499efbc0fc6d2994319624fc67R21) which happens way after the upstream checkout. At the time of writing this issue I thought I need to patch the source files pre-/during said upstream checkout/preparation where I only have the patch tooling available, but this was not needed and the build stays reproducible.
