### ISSUE TITLE
Login with device in v2024.5.0

### ISSUE THREAD

**Issue by ecesarini** [dani-garcia/bw_web_builds#165]
Hi
updating web-vault to v2024.5.0, after inserting email address there's **Login with device** option. 
Is it expected or maybe something went wrong in the build? 

![bitwarden-device-login](https://github.com/dani-garcia/bw_web_builds/assets/73652902/471669ee-3ecb-4a9c-b438-823d26265077)

Thank you very much

**Comment by BlackDex** [comment]
This is expected, as this is a feature of Bitwarden which Vaultwarden has implemented.
