### ISSUE TITLE
Error patching

### ISSUE THREAD

**Issue by iLikeToCode** [dani-garcia/bw_web_builds#178]
it patches down to tsconfig.json then fails at like 56, exit code 1 (the apply patch script)

**Comment by iLikeToCode** [comment]
It compiles fine in docker

**Comment by iLikeToCode** [comment]
it says it fails, but seems to work anyway
it exits with code 1

**Comment by BlackDex** [comment]
Please describe a bit better in details what you do and when this happens?
You say via docker it builds fine, so which steps do you take to build locally?

And which versions of npm/node are you using and are they matching what is shown during the docker build.

**Comment by iLikeToCode** [comment]
@BlackDex it seems as though it works, but finishes with error code 1
I am not make build(ing), I’m make checkout and make patch-web-vault
When I make docker-extract, all fine, no errors

**Comment by iLikeToCode** [comment]
<img width="414" alt="image" src="https://github.com/user-attachments/assets/6a500bfe-adb1-4cbe-8d32-6cb9a77c8cc7">
SEEMS to run fine, but exits with error code 1, no visible error.

**Comment by BlackDex** [comment]
you are probably not using the correct patch file with the correct web-vault checkout.
If they do not match it could be having some differences and therefore not fully patched. It does show which files were not able to be patched.

This is normal and not a bug.

**Comment by iLikeToCode** [comment]
? I pulled the latest today and used the make command so it automatically got the patch file

**Comment by BlackDex** [comment]
But which web-vault did you checked out?
We do not support any newer version then there are patch files for

**Comment by iLikeToCode** [comment]
I just used make checkout from this repl

**Comment by BlackDex** [comment]
And then what did you provided? `make checkout` requests user input.

**Comment by iLikeToCode** [comment]
Just ‘main’

**Comment by iLikeToCode** [comment]
2024.7.2 is out now, I entered 2024.6.2 (latest patch file name) and I’ll see if it works

**Comment by iLikeToCode** [comment]
Seems to work, do you know how I can specify that version in the make command

**Comment by BlackDex** [comment]
define a env variable `VAULT_VERSION="web-v2024.6.2"` or `VAULT_VERSION="e2354e8694ab5e532d04f275e4bd6bf560c7509b"`

If you do that it will use that version.

**Comment by iLikeToCode** [comment]
worked, thanks
