### ISSUE TITLE
web-2024.8.3

### ISSUE THREAD

**Issue by Timshel** [dani-garcia/bw_web_builds#181]
Hey,

Recently made a build based on the `v2024.8.3`, no idea if you already started working on it but wanted to share the main diff I found: 

 - SVG icons are now included in the Typescript ( [logo](https://github.com/bitwarden/clients/blob/web-v2024.8.3/libs/auth/src/angular/icons/bitwarden-logo.icon.ts) + [shield](https://github.com/bitwarden/clients/blob/web-v2024.8.3/libs/auth/src/angular/icons/bitwarden-shield.icon.ts) )
 - The deletion in `apps/web/src/app/oss-routing.module.ts` from the patch now completely broke my build  (I'm not familiar enough with angular to be sure why).
 - Not a direct impact but the `allow all collection` disappeared in the collection screen 
 
 Decided to stop using the patch method so all change I made can be seen [here](https://github.com/Timshel/oidc_web_vault/commits/v2024.8.3-3).

**Comment by BlackDex** [comment]
Not sure what we need to do with this.

The main reason we are stuck on 2024.6.2 is because of all rolls and right changes regarding to flexible collections and the manager role not existing anymore. That is why you are missing the `allow all collections`, which is mentioned on several places already.

**Comment by stefan0xC** [comment]
Thanks for the hints. I was aware of (most of) them already as I tried to update to v2024.7+ (cf. #169 I reverted back to `v2024.6.2` due the changes - i.e. the complete removal of the `Manager` role etc.)
