### ISSUE TITLE
Redesign UI

### ISSUE THREAD

**Issue by CustomIcon** [dani-garcia/bw_web_builds#187]
Last night BW web client has been updated:
![{026A6428-B4C4-4468-B3A1-21A70D22BA72}](https://github.com/user-attachments/assets/1d2e0eab-7da8-449a-84ad-4092f40a1fd9)

![{59E85B52-F8D6-47A5-A0BC-41146F2D7FD6}](https://github.com/user-attachments/assets/fb702c5c-253f-4a0b-9272-a049b225a892)

Will we be getting an Update soon to vaultwarden frontend as well?

**Comment by BlackDex** [comment]
If you checked the pending PR's you would see that there is at least one PR which mentions a newer version. 

Not sure if we will switch to this latest one yet, since we tested the one in the PR.

Keep in mind that Vaultwarden will probably always lag behind.
