### ISSUE TITLE
Release 2.16.1 is missing the attached web vault build

### ISSUE THREAD

**Issue by vollkorn1982** [dani-garcia/bw_web_builds#19]
Up until version 2.16.0b the release have attached a download with the compiled web build as a .tar.gz ready to install. The release 2.16.1 is missing this build. I would like to see the build attached to this release tag as well.

See https://github.com/dani-garcia/bw_web_builds/tags for a comparison ("download" is missing on release 2.16.1)

**Comment by dani-garcia** [comment]
Sorry, left the docker build running with the intention to upload it after then forgot, it's uploaded now.
