### ISSUE TITLE
Patch does not apply

### ISSUE THREAD

**Issue by CreepingDevil** [dani-garcia/bw_web_builds#27]
Hey,
i've tried to update the Web to v2.18.1 but when applying the patch it get this message:

> 2021-02-07 21:13:10 (32,8 MB/s) - ‘v2.18.1.patch’ saved [6870/6870]
> 
> error: patch failed: src/app/services/services.module.ts:135
> error: src/app/services/services.module.ts: patch does not apply

Am I doing something wrong?

**Comment by foxconndmd** [comment]
npm run sub:init

**Comment by BlackDex** [comment]
I think this can be closed.
See the Dockerfile for all the commands needed to run.

**Comment by BlackDex** [comment]
@w22gb8 (Or @dani-garcia ) would you be so kind to close this issue?
Thanks!
