### ISSUE TITLE
Patch to mask Authenticator Key (TOTP) field?

### ISSUE THREAD

**Issue by avoidik** [dani-garcia/bw_web_builds#29]
Hello,

Not sure why this field hasn't been created as sensitive in the first place, would it be possible to introduce one more patch to make it so?

Regards

**Comment by jjlin** [comment]
It's debatable how sensitive this field is since its useful life is pretty short, but I don't think we're going to diverge from upstream behavior here. You can make your case at https://community.bitwarden.com/c/feature-requests/5 if you feel strongly about it.

**Comment by avoidik** [comment]
I agree it would be better to raise my concern upstream, thank you
