### ISSUE TITLE
Patch not working

### ISSUE THREAD

**Issue by knightian** [dani-garcia/bw_web_builds#35]
tag v2.19.0 when applying patch of same version it is not hiding the Enterprise SSO button on the web vault and I see these errors:

error: patch failed: src/app/app.component.ts:140
error: src/app/app.component.ts: patch does not apply
error: patch failed: src/app/services/services.module.ts:136
error: src/app/services/services.module.ts: patch does not apply
error: src/app/settings/two-factor-u2f.component.ts: No such file or directory

**Comment by dani-garcia** [comment]
That patch works for me:

```sh
git clone --recurse-submodules https://github.com/bitwarden/web.git web-vault
cd web-vault
git checkout v2.19.0
git submodule update --recursive --init

git apply "../patches/v2.19.0.patch"
```

**Comment by knightian** [comment]
> That patch works for me:
> 
> ```shell
> git clone --recurse-submodules https://github.com/bitwarden/web.git web-vault
> cd web-vault
> git checkout v2.19.0
> git submodule update --recursive --init
> 
> git apply "../patches/v2.19.0.patch"
> ```

Yea dunno wtf I did but following those instructions worked thanks

**Comment by JohnFlowerful** [comment]
Perhaps update [wiki instructions regarding the web vault](https://github.com/dani-garcia/bitwarden_rs/wiki/Building-binary#install-the-web-vault) to reflect the need to update submodules.
