### ISSUE TITLE
customization of css

### ISSUE THREAD

**Issue by beppe9000** [dani-garcia/bw_web_builds#36]
I see [this](https://bitwardenrs.discourse.group/t/bitwarden-web-own-css/506) and [this](https://github.com/dani-garcia/bitwarden_rs/issues/246#issuecomment-826972744). I suggest to add an empty-by-default `custom.css` file for injecting custom css by mounting the file with docker.

It would be invoked by adding the appropriate code inside the html (`<link>` tag) or on top of one css file (`@import`) that gets always loaded.

**Comment by brandonkal** [comment]
Why not just add it in your custom Docker build?

```Dockerfile
RUN cat /web-vault/app/custom.css >> /web-vault/app/main.*.css
```

Avoids an unnecessary and unused http request for the 99%.

**Comment by beppe9000** [comment]
nice one
