### ISSUE TITLE
Latest patch 2.21.1 is busted

### ISSUE THREAD

**Issue by knightian** [dani-garcia/bw_web_builds#44]
npm wont build it:

<img width="1049" alt="Screen Shot 2021-07-26 at 6 20 20 am" src="https://user-images.githubusercontent.com/72685601/126912321-4d2da14e-7de6-4811-a46e-40a6a6a74372.png">

**Comment by knightian** [comment]
@dani-garcia some files missing again?

**Comment by BlackDex** [comment]
It works fine. At least if you use the docker build.
The shell script has some issues.

**Comment by knightian** [comment]
> It works fine. At least if you use the docker build.
> The shell script has some issues.

I'm building it from source not using docker.

**Comment by knightian** [comment]
```
cd /home/knightian/
git clone https://github.com/bitwarden/web.git --recursive
sudo chown knightian:knightian web/ -R
cd /home/knightian/web/
git submodule update --init --recursive
read -p "Type web tag name (e.g. v2.20.1): " tag
git checkout $tag
git submodule update --init --recursive
wget https://raw.githubusercontent.com/dani-garcia/bw_web_builds/master/patches/$tag.patch
git apply $tag.patch
npm run sub:init
npm install
npm audit fix
npm run dist
```

**Comment by BlackDex** [comment]
That's what o thought.
Node needs to be v14 at least, and npm needs to be v7.
If you have that it should work.

Also, try to use `npm ci` instead of `npm install`.

**Comment by knightian** [comment]
Ah righto my node is 12.2 or so

**Comment by knightian** [comment]
@BlackDex yep updating the things and using ci instead of install has resolved thanks
