### ISSUE TITLE
No "latest" image tag?

### ISSUE THREAD

**Issue by AlphaJack** [dani-garcia/bw_web_builds#61]
The server image on Docker Hub has many tags including "latest", why this is not possible for the web-vault image?

**Comment by BlackDex** [comment]
The web-vault and the vaultwarden server images are kinda linked to each other.
You can not always use the latest version of the web-vault with all versions of the vaultwarden docker image.
The only reason there are Docker images available for this web-vault is to have an easy integration with the vaultwarden docker images, and we want to specifically match those, and never use something like `latest`

**Comment by AlphaJack** [comment]
Understood, thanks.
