### ISSUE TITLE
how are assets created?

### ISSUE THREAD

**Issue by tessus** [dani-garcia/bw_web_builds#90]
I have noticed that the 2 additional assets 

- bw_web_v2022.X.Y.tar.gz
- bw_web_v2022.X.Y.tar.gz.asc 

are usually created 15-45 minutes after the release has been created.

I am just curious how these are created. Are they created by @dani-garcia manually or is there a hidden gh action that creates them?

**Comment by dani-garcia** [comment]
Once a release is made, Github Actions build and publish the docker container:

https://github.com/dani-garcia/bw_web_builds/actions/runs/3292215923

https://hub.docker.com/layers/vaultwarden/web-vault/v2022.10.1/images/sha256-02aebd82a8dda3c8c9606cb48f5fd9acdf5c9a422e09b72a9946bab522352215

That docker image contains the uncompressed web vault, as it's used on the official Vaultwarden docker image, plus a .tar.gz archive.

I simply extract that archive from the docker build, check that the version is correct and everything seems okay, sign it with my private key and upload it to the releases section.

So it's a semi-automated process.

**Comment by tessus** [comment]
Ah, I see. Thanks a bunch for the explanation.

I love automating things. Since the docker image is also automatically pushed to the public docker hub, wouldn't it be permissible to automate the rest as well?
If so, I can look into it when I have a bit more time.

**Comment by dani-garcia** [comment]
Sure thing! I've actually talked recently with @BlackDex about this, and it would be nice to have the archive upload with a separate checksum file automated. 

I can continue signing the releases manually in case anyone depends on that but having the artifacts uploaded faster is a win in my book.

**Comment by tessus** [comment]
In that case, please ping me, if you want me to look into it (unless either of you is already working on it). I can't commit to a specific date, but I'd love to help.

Closing this. My email is in my profile.
